USE `CPM`;

DROP TABLE IF EXISTS `CentroDeDatos`.`TemporalUno`;
CREATE TABLE TemporalUno(
INVENTO VARCHAR(255) ,
INVENTOR VARCHAR(255) ,
PROFESIONAL_ASIGANDO_AL_INVENTO VARCHAR(255) ,
EL_PROFESIONAL_ES_JEFE_DEL_AREA VARCHAR(255) ,
FECHA_CONTRATO_PROFESIONAL DATE ,
SALARIO INT ,
COMISION INT ,
AREA_INVEST_DEL_PROF VARCHAR(255) ,
RANKING INT ,
ANIO_DEL_INVENTO INT ,
PAIS_DEL_INVENTO VARCHAR(255) ,
PAIS_DEL_INVENTOR VARCHAR(255) ,
REGION_DEL_PAIS VARCHAR(255) NOT NULL,
CAPITAL VARCHAR(255) NOT NULL,
POBLACION_DEL_PAIS INT NOT NULL,
AREA_EN_KM2 INT NOT NULL,
FRONTERA_CON VARCHAR(255) ,
NORTE CHAR(1) ,
SUR CHAR(1) ,
ESTE CHAR(1) ,
OESTE CHAR(1) 
);

LOAD DATA INFILE '/var/lib/mysql-files/uno.csv'
INTO TABLE TemporalUno
character set utf8mb4 
fields terminated by ',' 
optionally enclosed by '\''
lines terminated by '\n'
ignore 1 lines
(
@INVENTO,
@INVENTOR,
@PROFESIONAL_ASIGANDO_AL_INVENTO,
@EL_PROFESIONAL_ES_JEFE_DEL_AREA,
@FECHA_CONTRATO_PROFESIONAL,
@SALARIO,
@COMISION,
@AREA_INVEST_DEL_PROF,
@RANKING,
@ANIO_DEL_INVENTO,
@PAIS_DEL_INVENTO,
@PAIS_DEL_INVENTOR,
@REGION_DEL_PAIS,
@CAPITAL,
@POBLACION_DEL_PAIS,
@AREA_EN_KM2,
@FRONTERA_CON,
@NORTE,
@SUR,
@ESTE,
@OESTE  
)
set
INVENTO = nullif(@INVENTO, ''),
INVENTOR = nullif(@INVENTOR, ''),
PROFESIONAL_ASIGANDO_AL_INVENTO = nullif(@PROFESIONAL_ASIGANDO_AL_INVENTO, ''),
EL_PROFESIONAL_ES_JEFE_DEL_AREA = nullif(@EL_PROFESIONAL_ES_JEFE_DEL_AREA, ''),
FECHA_CONTRATO_PROFESIONAL = nullif(@FECHA_CONTRATO_PROFESIONAL, ''),
SALARIO = nullif(@SALARIO, ''),
COMISION = nullif(@COMISION, ''),
AREA_INVEST_DEL_PROF = nullif(@AREA_INVEST_DEL_PROF, ''),
RANKING = nullif(@RANKING, ''),
ANIO_DEL_INVENTO = nullif(@ANIO_DEL_INVENTO, ''),
PAIS_DEL_INVENTO = nullif(@PAIS_DEL_INVENTO, ''),
PAIS_DEL_INVENTOR = nullif(@PAIS_DEL_INVENTOR, ''),
REGION_DEL_PAIS = nullif(@REGION_DEL_PAIS, ''),
CAPITAL = nullif(@CAPITAL, ''),
POBLACION_DEL_PAIS = nullif(@POBLACION_DEL_PAIS, ''),
AREA_EN_KM2 = nullif(@AREA_EN_KM2, ''),
FRONTERA_CON = nullif(@FRONTERA_CON, ''),
NORTE = nullif(@NORTE, ''),
SUR = nullif(@SUR, ''),
ESTE = nullif(@ESTE, ''),
OESTE = nullif(@OESTE, '')
;


DROP TABLE IF EXISTS `CentroDeDatos`.`TemporalDos`;
CREATE TABLE TemporalDos(
NOMBRE_ENCUESTA VARCHAR(255) NOT NULL,
PREGUNTA VARCHAR(255) NOT NULL,
RESPUESTAS_POSIBLES VARCHAR(255) NOT NULL,
RESPUESTA_CORRECTA  VARCHAR(255) , -- aqui hacer algo cuando venga null 
PAIS VARCHAR(255) NOT NULL,
RESPUESTA_PAIS VARCHAR(255) NOT NULL
);

LOAD DATA INFILE '/var/lib/mysql-files/dos.csv'
INTO TABLE TemporalDos
character set utf8mb4 
fields terminated by ',' 
optionally enclosed by '\''
lines terminated by '\n'
ignore 1 lines
(
@NOMBRE_ENCUESTA,
@PREGUNTA,
@RESPUESTAS_POSIBLES,
@RESPUESTA_CORRECTA, 
@PAIS,
@RESPUESTA_PAIS
)
set
NOMBRE_ENCUESTA = nullif(@NOMBRE_ENCUESTA , ''),
PREGUNTA = nullif(@PREGUNTA , ''),
RESPUESTAS_POSIBLES = nullif(@RESPUESTAS_POSIBLES , ''),
RESPUESTA_CORRECTA  = nullif(@RESPUESTA_CORRECTA , ''), 
PAIS = nullif(@PAIS , ''),
RESPUESTA_PAIS = nullif(@RESPUESTA_PAIS , '')
;


DROP TABLE IF EXISTS `CentroDeDatos`.`TemporalTres`;
CREATE TABLE TemporalTres(
NOMBRE_REGION VARCHAR(255) NOT NULL,
REGION_PADRE VARCHAR(255)
);

LOAD DATA INFILE '/var/lib/mysql-files/tres.csv'
INTO TABLE TemporalTres
character set utf8mb4 
fields terminated by ',' 
optionally enclosed by '\''
lines terminated by '\n'
ignore 1 lines
(
@NOMBRE_REGION,
@REGION_PADRE 
)
set
NOMBRE_REGION = nullif(@NOMBRE_REGION , ''),
REGION_PADRE = nullif(@REGION_PADRE , '')
;
